### ISSUE TITLE
The errors of multi-GPU training

### ISSUE THREAD

**Issue by xjhjinhui** [RoyalVane/MMAN#4]
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    model.optimize_parameters()
  File "/home/o1/Royal/MMAN/models/pix2pix_model.py", line 287, in optimize_parameters
    self.forward()
  File "/home/o1/Royal/MMAN/models/pix2pix_model.py", line 170, in forward
    self.fake_B_GAN = self.netG(self.real_A)['GAN'] #multi-channel label map--> target real_B_GAN
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/o1/Royal/MMAN/models/networks.py", line 415, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 119, in data_parallel
    return gather(outputs, output_device, dim)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 65, in gather
    return gather_map(outputs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 60, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
ValueError: dictionary update sequence element #0 has length 30; 2 is required

Excuse me,I wonder how can I solve these errors?
The command is “python3 train.py --dataroot ../Human --dataset LIP --name Exp_0 --output_nc 20 --gpu_ids 0,1 --pre_trained --loadSize 286 --fineSize 256
”

**Comment by RoyalVane** [comment]
We have not trained or tested the MMAN on multi GPUs because a single gpu is able to train the model. If you want to do this, please slightly modify the code by yourself.

**Comment by xjhjinhui** [comment]
Thanks for your reply.
